version: '3'

services:
  buildtools:
    image: ghcr.io/electron/devcontainer:27db4a3e3512bfd2e47f58cea69922da0835f1d9
    labels:
      shipyard.route: '/'
    volumes:
      - ..:/workspaces/gclient/src/electron:cached
      - /var/run/docker.sock:/var/run/docker.sock 
    command: /bin/sh -c "while sleep 1000; do :; done"  
    user: builduser
    ports:
      - 8088
      - 6080
      - 5901
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
